fix:
    rule:
        # block_400: all
        alias_declaration_503: all
        architecture_007: all
        architecture_008: all
        architecture_010: all
        architecture_015: all
        architecture_016: all
        architecture_017: all
        architecture_018: all
        architecture_024: all
        architecture_026: all
        architecture_400: all
        architecture_600: all
        architecture_601: all
        assert_001: all
        assert_002: all
        assert_003: all
        assert_004: all
        assert_005: all
        assert_400: all
        attribute_declaration_300: all
        attribute_declaration_501: all
        attribute_specification_300: all
        attribute_specification_501: all
        block_002: all
        block_007: all
        block_201: all
        block_202: all
        block_300: all
        block_301: all
        block_302: all
        block_comment_001: all
        block_comment_003: all
        case_005: all
        case_200: all
        constant_013: all
        comment_010: all
        comment_100: all
        component_021: all
        component_022: all
        concurrent_001: all
        concurrent_005: all
        concurrent_006: all
        concurrent_008: all
        entity_015: all
        entity_016: all
        entity_017: all
        entity_018: all
        entity_019: all
        entity_600: all
        function_008: all
        function_010: all
        function_012: all
        function_018: all
        function_019: all
        function_020: all
        function_100: all
        generate_001: all
        generate_007: all
        generate_011: all
        generate_403: all
        generic_003: all
        generic_map_006: all
        if_001: all
        if_014: all
        instantiation_001: all
        instantiation_003: all
        instantiation_010: all
        library_008: all
        package_007: all
        package_011: all
        package_012: all
        package_014: all
        package_019: all
        package_400: all
        package_body_002: all
        package_body_003: all
        port_002: all
        port_003: all
        port_004: all
        port_007: all
        port_008: all
        port_014: all
        port_015: all
        port_020: all
        port_024: all
        port_map_004: all
        procedure_004: all
        procedure_012: all
        procedure_013: all
        procedure_014: all
        procedure_100: all
        procedure_401: all
        procedure_410: all
        procedure_411: all
        procedure_507: all
        procedure_call_001: all
        process_002: all
        process_006: all
        process_011: all
        process_012: all
        process_014: all
        process_015: all
        process_018: all
        process_021: all
        process_022: all
        process_027: all
        process_031: all
        process_033: all
        process_400: all
        record_type_definition_005: all
        record_type_definition_005: all
        record_type_definition_006: all
        record_type_definition_200: all
        sequential_001: all
        signal_001: all
        signal_014: all
        # signal_400 does strange alignment for signals of type record with multi-line definitions.
        signal_400: all
        subprogram_body_205: all
        subtype_002: all
        type_014: all
        type_501: all
        type_400: all
        variable_001: all
        variable_011: all
        whitespace_001: all
        whitespace_003: all
        whitespace_004: all
        whitespace_005: all
        whitespace_006: all
        whitespace_100: all
        whitespace_200: all